### ISSUE TITLE
[Kind request] Update project

### ISSUE THREAD

**Issue by MikeDabrowski** [szchenghuang/react-transitions#4]
Currently, using this module produces following warnings.
```
Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.  bundle.js:81283:16
Warning: Portal: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.
```
Although they're just a warnings, it might be good to update this project to meet new rules.

**Comment by szchenghuang** [comment]
It should have been [updated](https://github.com/szchenghuang/react-transitions/commit/c9119ef17f3a71ac418137137a1dbeb99f1d5d52) to get rid of the warning since the latest release v0.0.3. If you are present the warning against that version, please let me know. Thanks!

**Comment by MikeDabrowski** [comment]
Yes, I updated to the newest 0.0.3 but still have this problem. I made custom adjustments to your code, but that were mostly css-related changes.

**Comment by MikeDabrowski** [comment]
Yeah, it shows this
![image](https://cloud.githubusercontent.com/assets/17836911/26643254/0b04ef6e-4631-11e7-9903-81b47ae039cf.png)
which is not particularly helpful

**Comment by MikeDabrowski** [comment]
I combed through my project and removed all remains of previous version - warnings still persist. But I created blank project and no warnings there. So I believe it is my fault then.

**Comment by szchenghuang** [comment]
In general tracing the call stack to find out where errors/warnings are resulted from is helpful. [Here](https://developers.google.com/web/updates/2015/07/print-out-a-quick-stack-trace-from-the-console) is one of resources on how to trace it.

Regarding to the dependencies to deprecated `xxx-transition-group`, it should be improved indeed. Let's trace it in a newly created [issue #5](https://github.com/szchenghuang/react-transitions/issues/5) and leave this current one to `PropTypes` and `React.createClass`.
