### ISSUE TITLE
Replace deprecated react-addon-transition-group with react-transition-group

### ISSUE THREAD

**Issue by szchenghuang** [szchenghuang/react-transitions#5]
Targeted deprecated dependencies:

    "react-addons-css-transition-group": "^15.3.1"
    "react-addons-transition-group": "^15.3.1"

**Comment by MikeDabrowski** [comment]
Dependencies listed here have their successor - [react-transition-group](https://github.com/reactjs/react-transition-group). However, simply swapping imports to that new module produces long list of errors.

This month I will not be able to do much about this (finals incoming), but I may try to track them down next month.
